# Generated by Django 3.2.4 on 2021-10-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_news_newsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appName', models.CharField(max_length=80)),
                ('imagePath', models.URLField()),
                ('googlePath', models.URLField()),
                ('applePath', models.URLField()),
                ('otherPath', models.URLField()),
            ],
        ),
    ]
