# Generated by Django 3.2.4 on 2021-10-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_appmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodel',
            name='applePath',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='googlePath',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='imagePath',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='otherPath',
            field=models.URLField(null=True),
        ),
    ]
