# Generated by Django 3.2.4 on 2021-10-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_profilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramingCareerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='QualificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDaysModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
